### ISSUE TITLE
Approximating Bézier curves with circular arcs

### ISSUE THREAD

**Issue by splace** [Pomax/bezierinfo#60]
my guess is that the algorithm for finding the required arcs wouldn't work for tight turns.

so i made the demo have a tight turn;

![screenshot from 2015-06-21 20 43 20](https://cloud.githubusercontent.com/assets/1234848/8273107/af6996f0-1856-11e5-996a-36ff3e97fb51.png)

**Comment by Pomax** [comment]
it's more likely I have a bug in which of the two arc points is the start and end - it looks like that ginormous arc should have start and end switch. I'm about to head off to a week long work meetup, but I'll file this as bug and hopefully get to it next weekend.

**Comment by splace** [comment]
i've been thinking some more; 
my issue with the algorithm is that the five point 'fit' to the arc might have the possibility of 'missing' rapid changes between the points, possibly falsely indicating a smooth curve.
but now i think that with lower order beziers, say quad and cubic, since there is only the possibility of one/two tight turns the algorithm is probably stable, 
but above that there seems the possibility of 'missing' rapid changes.
it might be that you need as many test points as the order of the bezier.

**Comment by Pomax** [comment]
to work for arbitrary order curves, we'd need to find all the inflection points and then, really, perform arc approximations that terminate at inflections. For quadratic and cubic curves we can get away by not doing that, because the error between arc and curve as we try larger and large arcs always results in an overestimation error on one side, and an underestimation on the other. Once you hit quartic and up, that no longer holds, and you can "skip over" a point that *should* lead to a bad arc, to a point that suddenly no longer suggests a bad arc if we simply look at the errors between the two points.

You might be right that an nth order curve needs n points in order to verify a correct arc, although I'm not sure how they would have to be distributed over the arc to check for correctness. I suspect linear arc spacing would work, but that's not really based on any real mathematical investigation (yet?).

**Comment by Pomax** [comment]
closing here, and opening as https://github.com/Pomax/bezierjs/issues/18 on the relevant repo
